name: Packer-Frontend

on:
  push:
    branches:
      - master
    paths:
      - "src/packer/frontend/**"
      - "src/dotnet/frontend/**"

env:
  DOTNET_VERSION: "8.0" # The .NET SDK version to use
  PACKER_VERSION: "1.11.0" # The version of Packer to use
  WORKING_DIRECTORY: "./src/packer/frontend"
  DOTNET_WORKING_DIRECTORY: "./src/dotnet/frontend/FleetPortal"
  REGISTRY: ghcr.io
  IMAGE_NAME: localstack-ec2/frontend-ami
  VERSION: "1.0.0"

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}

      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}

      - name: Publish
        run: |
          pwd
          ls
          dotnet publish ./FleetPortal.csproj -c Release -o ./publish
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}

      - name: Generate the Deployment Package
        run: |
          zip -r ../deployment.zip ./
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}/publish

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ env.DOTNET_WORKING_DIRECTORY }}

      - name: Upload Deployment Package
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-deployment
          path: ${{ env.DOTNET_WORKING_DIRECTORY }}/deployment.zip

  packer:
    needs: [frontend-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: dotnet-deployment

      - name: Check Files
        run: |
          pwd
          ls

      - id: image-version
        name: Generate Version Number
        run: |
          echo "version=$(date +'%Y.%m').${{ github.run_number }}" >> "$GITHUB_OUTPUT"

      - id: agent-ipaddress
        name: Check Path
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          ipaddress=$(curl -s http://checkip.amazonaws.com)
          echo $ipaddress
          echo "ipaddress=$ipaddress" >> "$GITHUB_OUTPUT"

      - name: Copy Deployment Package
        run: |
          cp ./deployment.zip ${{ env.WORKING_DIRECTORY }}/deployment.zip

      - name: Check Files
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          pwd
          ls

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: setup
        name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - id: build
        name: Packer Build
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PKR_VAR_image_version: ${{ steps.image-version.outputs.version }}
          PKR_VAR_agent_ipaddress: ${{ steps.agent-ipaddress.outputs.ipaddress }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          packer init ./
          packer build ./
          #packer build -var-file=variables.pkrvars.hcl ./

      - name: Tag the built Docker image
        run: |
          docker tag docker.ubuntu ${{ env.REGISTRY }}/${{ github.repository }}/my-app-image:${{ github.sha }}
        # Get the image ID from Packer's build output (manual parsing might be needed for complex outputs)
        # Assuming the image is tagged by Packer, we can retag it for GitHub Packages
        # A better approach is to use the `docker` command after the Packer build
        # Example command to retag the image (adjust image name as needed)
        # docker tag <packer-built-image-id> ghcr.io/${{ github.repository }}/my-app-image:${{ github.sha }}

      - name: Push Docker image to GitHub Packages
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}/my-app-image:${{ github.sha }}
        #run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
